services:
  # Frontend Service
  - type: web
    name: divine-whispers-frontend
    runtime: docker
    dockerfilePath: ./divine-whispers-frontend/Dockerfile
    dockerContext: .
    region: oregon
    plan: free

    # Branch to deploy from
    branch: main

    # Health check endpoint
    healthCheckPath: /health

    # Docker build arguments (passed to Dockerfile ARG)
    dockerCommand: docker build --build-arg BACKEND_URL=https://divine-whispers-backend.onrender.com -f divine-whispers-frontend/Dockerfile -t divine-whispers-frontend .

    # Environment variables (not needed for build, but keeping for reference)
    envVars:
      - key: BACKEND_URL
        value: https://divine-whispers-backend.onrender.com

  # Backend API Service
  - type: web
    name: divine-whispers-backend
    runtime: docker
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: .
    region: oregon  # Change to your preferred region
    plan: free  # Completely free, no credit card required

    # Branch to deploy from
    branch: main

    # Build command (runs build.sh)
    buildCommand: bash Backend/build.sh

    # Health check endpoint
    healthCheckPath: /health

    # Environment variables (set these in Render dashboard)
    envVars:
      # === CRITICAL: Set these in Render Dashboard ===
      - key: SECRET_KEY
        generateValue: true  # Render will auto-generate a secure key

      - key: DEBUG
        value: false

      - key: PYTHON_VERSION
        value: 3.11

      # Database (auto-provided by Render when you add PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: divine-whispers-db
          property: connectionString

      # === SET THESE MANUALLY in Render Dashboard ===
      - key: OPENAI_API_KEY
        sync: false  # Must be set manually

      - key: LLM_MODEL
        value: gpt-3.5-turbo

      - key: LLM_PROVIDER
        value: openai

      # Email settings (Zoho)
      - key: SMTP_HOST
        value: smtp.zoho.com

      - key: SMTP_PORT
        value: 587

      - key: SMTP_USER
        sync: false  # Must be set manually

      - key: SMTP_PASSWORD
        sync: false  # Must be set manually

      - key: FROM_EMAIL
        sync: false  # Same as SMTP_USER

      - key: FROM_NAME
        value: Divine Whispers

      - key: SUPPORT_EMAIL
        sync: false  # Set manually

      # ChromaDB settings
      - key: CHROMA_DB_PATH
        value: /opt/render/project/src/chroma_db

      - key: CHROMA_COLLECTION_NAME
        value: fortune_knowledge

      # CORS - automatically reference frontend service
      # Use comma-separated string for multiple hosts
      - key: ALLOWED_HOSTS
        fromService:
          name: divine-whispers-frontend
          type: web
          property: host

      # App settings
      - key: DEFAULT_USER_POINTS
        value: 100

      - key: FORTUNE_DRAW_COST
        value: 10

      - key: FORTUNE_INTERPRET_COST
        value: 15

      - key: LOG_LEVEL
        value: INFO

      # Frontend URL - automatically reference frontend service
      - key: FRONTEND_URL
        fromService:
          name: divine-whispers-frontend
          type: web
          property: host

# PostgreSQL Database
databases:
  - name: divine-whispers-db
    databaseName: divine_whispers
    user: divine_whispers_user
    region: oregon  # Same region as your web service
    plan: free  # Completely free, 256MB storage, no credit card required

    # PostgreSQL version
    ipAllowList: []  # Empty = public access (secured by password)

# Notes:
# ======
# 1. After creating this service, manually set these env vars in Render dashboard:
#    - OPENAI_API_KEY
#    - SMTP_USER
#    - SMTP_PASSWORD
#    - FROM_EMAIL
#    - SUPPORT_EMAIL
#    - FRONTEND_URL (after frontend deploys)
#
# 2. Update ALLOWED_HOSTS after frontend deploys:
#    https://your-frontend.onrender.com
#
# 3. ChromaDB data will be copied during Docker build
#    It's stored in the container filesystem (ephemeral on free tier)
#    For persistent storage, upgrade to a paid plan with disk storage
#
# 4. To deploy:
#    - Push this file to your Git repository
#    - Go to render.com dashboard
#    - Create "New" -> "Blueprint"
#    - Connect your repository
#    - Render will auto-detect render.yaml
